### ISSUE TITLE
clip 受到 image 的影响导致失效

### ISSUE THREAD

**Issue by boenfu** [rustq/vue-skia#19]
提个 issue 备忘，空了修修
![20230925095955_rec_](https://github.com/rustq/vue-skia/assets/33797740/c31b61c9-5404-43fa-872b-f49a399b7832)

**Comment by meloalright** [comment]
确实 🤔

**Comment by meloalright** [comment]
Perfect now 🎉

https://651a8d532e43b26c8b393bcc--vue-skia.netlify.app
